### ISSUE TITLE
Generate ROS map using Pepper robot

### ISSUE THREAD

**Issue by raulperula** [LCAS/spqrel_navigation#9]
Hello,
I read that it is necessary to previously have a map in ROS format in order to use the library.
My question is: have you created a map with the Pepper robot directly using the **naoqi_driver bridge** or **another robot**?
Thanks. Best regards,
Raúl

**Comment by mtlazaro** [comment]
Dear Raúl,

Up to now we don't have a mapping system for the Pepper, and using its laser using the ROS bridge doesn't give nice results due to its low accuracy.

For this reason, we always used another robot to build a map. If you don't have other robot you can try to use the depth camera from the Pepper and try to extract some scan from it using ROS tools.

Best,
Mayte.

**Comment by raulperula** [comment]
Ok, thank you for your answers.
